
language: objective-c
matrix:
  include:
    - osx_image: xcode10.2
      objective-c: "stable"

before_script:
  carthage update --cache-builds
script:
  xcodebuild test -project Blockly.xcodeproj -scheme BlocklyTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.2'
